name: EduPay CD (Render Deploy)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build # Nécessite que le job de build/CI passe d'abord (en théorie)
    
    steps:
    - name: Trigger Render Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        method: 'POST'
        timeout: 10000
